Декоративные элементы
htmlacademy-htmlcss/1570079-nerds-29 pull request #11
Opened 2020-10-03 19:01 UTC by LeonidX777

Главная страница

2020-10-03 20:34 UTC, SidSpears69 requested changes
Все отступы и размеры элементов в соответствии с макетом

2020-10-07 19:08 UTC, LeonidX777 commented
Декоративные элементы

2020-10-07 20:33 UTC, SidSpears69 reviewed
Улучшить внешний вид шапки под макет, преимущества растянуть по сетке, футер под макет

2020-10-07 20:33 UTC, SidSpears69 commented on index.html
>  <footer class="page-footer main-footer">
Зачем столько секций в футере? убрать ненужные, в целом проработать разметку футера

2020-10-09 11:55 UTC, SidSpears69 reviewed
Стилизовать основную часть страницы под макет, добавить отступы, в соответствии с макетом, проверить размеры блоков, добавить недостающие декоративные элементы, проработать разметку в футере и поправить социальные иконки в нем

2020-10-11 20:47 UTC, merged