Разметка
htmlacademy-htmlcss/1570079-nerds-29 pull request #2
Opened 2020-09-12 10:31 UTC by LeonidX777

Разметка главной страницы

2020-09-12 12:07 UTC, SidSpears69 commented on index.html
> +      <p><strong>Мы-маленькая, но гордая дизайн-студия из Краснодара.</strong></p>
Зачем нужен тег strong?

2020-09-12 12:07 UTC, SidSpears69 commented on index.html
> +            <button type="button">Заказать</button>
То же что и в первом комментарии

2020-09-12 12:07 UTC, SidSpears69 commented on index.html
> +            <button type="button">Заказать</button>
То же что и в первом комментарии

2020-09-12 12:07 UTC, SidSpears69 commented on index.html
> +          <h2>Выполняем заказы на разработку:</h2>
Что-то непонятное с заголовками в списке, должны ли они быть заголовками или это просто текст?

2020-09-12 12:07 UTC, SidSpears69 commented on index.html
> +<p>Репозиторий создан для обучения на профессиональном онлайн‑курсе «<a href="https://htmlacademy.ru/intensive/htmlcss">HTML
Удалить

2020-09-12 12:07 UTC, SidSpears69 commented on index.html
> +<footer>
А где блок с картой и контактами?

2020-09-12 12:07 UTC, SidSpears69 commented on index.html
> +  <section>
Для чего вкладывать ссылки на соцсети в отдельную секцию?

2020-09-12 15:05 UTC, LeonidX777 commented on index.html
> +    <button type="button">Узнать больше</button>
Значит ссылка

2020-09-14 12:56 UTC, SidSpears69 requested changes
Уже лучше, разберись с футером

2020-09-14 18:59 UTC, merged